"""Create policies table

Revision ID: 35ec9ed4aac1
Revises: 83052ed8a0d9
Create Date: 2026-09-06 13:52:16.664787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ec9ed4aac1'
down_revision = '83052ed8a0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=100), nullable=False),
    sa.Column('allowed_region', sa.String(length=100), nullable=False),
    sa.Column('encryption_required', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classification')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policies')
    # ### end Alembic commands ###
