"""Create files table

Revision ID: 836005d99965
Revises: 35ec9ed4aac1
Create Date: 2026-09-06 13:56:29.206878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836005d99965'
down_revision = '35ec9ed4aac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('classification', sa.String(length=100), nullable=False),
    sa.Column('storage_region', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
